### ISSUE TITLE
Loose html outlines for major pages

### ISSUE THREAD

**Issue by mchaiken** [mchaiken/Event-Narwhal#9]
-New Event
-My Events
-Specific Event
-Settings
-pop-up window for changing yummly/8traks stuff maybe?

**Comment by jybaran** [comment]
* new event: clarify please. thought all event creation from facebook? is this pulling that in & adding 8tracks/yummly/etc?
* my events: should be basically set up
* specific event: has panels for 8tracks embed & whatever we end up doing with yummly, also clicking the headers will open settings page/pop-up
* settings: clarify (basically the same layout as new event or?)
* pop-up: have not worked with pop-ups before, will need to figure that out

**Comment by jybaran** [comment]
* new event: has space blocked out for pulling event from fb, entering theme & keywords for yummy/8tracks
* my events: looking good! miranda got for loop working
* specific event: 8tracks & yummly panels, need to add confirmed attendees, space for description probably?
* settings: basically copying new event code
* pop-up: no progress yet, might just scrap this & pull it into the settings page instead?

**Comment by jybaran** [comment]
* new event: scrapped, redirects to settings.html
* my_events: still seems functional
* specific event: added edit/delete buttons on the bottom of the page, those should be linked up but need backend work in app.py
* settings: should work now
* pop-up: sydney is dealing with that
